import type { ZCardType } from "./database";

export type NormalizedSsCard = {
  ss_number: string;
  status: string | null;
  company: string | null;
  unit: string | null;
  location_1: string | null;
  location_2: string | null;
  location_3: string | null;
  location_4: string | null;
  line: string | null;
  operation: string | null;
  ute_mapped: string | null;
  asset: string | null;
  requester_name: string | null;
  requester_email: string | null;
  user_name: string | null;
  main_subject: string | null;
  secondary_subject: string | null;
  z_type: ZCardType | null;
  description: string | null;
  machine_stopped: boolean | null;
  safety_item: boolean | null;
  created_at: string | null;
  classification: string | null;
  safety: string | null;
  production: string | null;
  quality: string | null;
  environment: string | null;
  cost_center: string | null;
  work_center: string | null;
  has_wcm_tag: boolean | null;
  wcm_pillar: string | null;
  om_number: string | null;
  om_status: string | null;
  om_service_type: string | null;
  om_service_nature: string | null;
  om_opened_at: string | null;
  om_description: string | null;
  om_closed_at: string | null;
  is_closed_for_operator: boolean;
  raw_data: Record<string, unknown>;
};
